package com.susion.rabbit.base.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.susion.rabbit.base.entities.RabbitIoCallInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RABBIT_IO_CALL_INFO".
*/
public class RabbitIoCallInfoDao extends AbstractDao<RabbitIoCallInfo, Long> {

    public static final String TABLENAME = "RABBIT_IO_CALL_INFO";

    /**
     * Properties of entity RabbitIoCallInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property InvokeStr = new Property(1, String.class, "invokeStr", false, "INVOKE_STR");
        public final static Property BecalledStr = new Property(2, String.class, "becalledStr", false, "BECALLED_STR");
        public final static Property Time = new Property(3, Long.class, "time", false, "TIME");
    }


    public RabbitIoCallInfoDao(DaoConfig config) {
        super(config);
    }
    
    public RabbitIoCallInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RABBIT_IO_CALL_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"INVOKE_STR\" TEXT," + // 1: invokeStr
                "\"BECALLED_STR\" TEXT," + // 2: becalledStr
                "\"TIME\" INTEGER);"); // 3: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RABBIT_IO_CALL_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RabbitIoCallInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String invokeStr = entity.getInvokeStr();
        if (invokeStr != null) {
            stmt.bindString(2, invokeStr);
        }
 
        String becalledStr = entity.getBecalledStr();
        if (becalledStr != null) {
            stmt.bindString(3, becalledStr);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(4, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RabbitIoCallInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String invokeStr = entity.getInvokeStr();
        if (invokeStr != null) {
            stmt.bindString(2, invokeStr);
        }
 
        String becalledStr = entity.getBecalledStr();
        if (becalledStr != null) {
            stmt.bindString(3, becalledStr);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(4, time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RabbitIoCallInfo readEntity(Cursor cursor, int offset) {
        RabbitIoCallInfo entity = new RabbitIoCallInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // invokeStr
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // becalledStr
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RabbitIoCallInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setInvokeStr(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBecalledStr(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RabbitIoCallInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RabbitIoCallInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RabbitIoCallInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
