package com.susion.rabbit.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.susion.rabbit.entities.RabbitAppStartSpeedInfo;
import com.susion.rabbit.entities.RabbitBlockFrameInfo;
import com.susion.rabbit.entities.RabbitExceptionInfo;
import com.susion.rabbit.entities.RabbitFPSInfo;
import com.susion.rabbit.entities.RabbitHttpLogInfo;
import com.susion.rabbit.entities.RabbitMemoryInfo;
import com.susion.rabbit.entities.RabbitPageSpeedInfo;
import com.susion.rabbit.entities.RabbitReportInfo;

import com.susion.rabbit.greendao.RabbitAppStartSpeedInfoDao;
import com.susion.rabbit.greendao.RabbitBlockFrameInfoDao;
import com.susion.rabbit.greendao.RabbitExceptionInfoDao;
import com.susion.rabbit.greendao.RabbitFPSInfoDao;
import com.susion.rabbit.greendao.RabbitHttpLogInfoDao;
import com.susion.rabbit.greendao.RabbitMemoryInfoDao;
import com.susion.rabbit.greendao.RabbitPageSpeedInfoDao;
import com.susion.rabbit.greendao.RabbitReportInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rabbitAppStartSpeedInfoDaoConfig;
    private final DaoConfig rabbitBlockFrameInfoDaoConfig;
    private final DaoConfig rabbitExceptionInfoDaoConfig;
    private final DaoConfig rabbitFPSInfoDaoConfig;
    private final DaoConfig rabbitHttpLogInfoDaoConfig;
    private final DaoConfig rabbitMemoryInfoDaoConfig;
    private final DaoConfig rabbitPageSpeedInfoDaoConfig;
    private final DaoConfig rabbitReportInfoDaoConfig;

    private final RabbitAppStartSpeedInfoDao rabbitAppStartSpeedInfoDao;
    private final RabbitBlockFrameInfoDao rabbitBlockFrameInfoDao;
    private final RabbitExceptionInfoDao rabbitExceptionInfoDao;
    private final RabbitFPSInfoDao rabbitFPSInfoDao;
    private final RabbitHttpLogInfoDao rabbitHttpLogInfoDao;
    private final RabbitMemoryInfoDao rabbitMemoryInfoDao;
    private final RabbitPageSpeedInfoDao rabbitPageSpeedInfoDao;
    private final RabbitReportInfoDao rabbitReportInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rabbitAppStartSpeedInfoDaoConfig = daoConfigMap.get(RabbitAppStartSpeedInfoDao.class).clone();
        rabbitAppStartSpeedInfoDaoConfig.initIdentityScope(type);

        rabbitBlockFrameInfoDaoConfig = daoConfigMap.get(RabbitBlockFrameInfoDao.class).clone();
        rabbitBlockFrameInfoDaoConfig.initIdentityScope(type);

        rabbitExceptionInfoDaoConfig = daoConfigMap.get(RabbitExceptionInfoDao.class).clone();
        rabbitExceptionInfoDaoConfig.initIdentityScope(type);

        rabbitFPSInfoDaoConfig = daoConfigMap.get(RabbitFPSInfoDao.class).clone();
        rabbitFPSInfoDaoConfig.initIdentityScope(type);

        rabbitHttpLogInfoDaoConfig = daoConfigMap.get(RabbitHttpLogInfoDao.class).clone();
        rabbitHttpLogInfoDaoConfig.initIdentityScope(type);

        rabbitMemoryInfoDaoConfig = daoConfigMap.get(RabbitMemoryInfoDao.class).clone();
        rabbitMemoryInfoDaoConfig.initIdentityScope(type);

        rabbitPageSpeedInfoDaoConfig = daoConfigMap.get(RabbitPageSpeedInfoDao.class).clone();
        rabbitPageSpeedInfoDaoConfig.initIdentityScope(type);

        rabbitReportInfoDaoConfig = daoConfigMap.get(RabbitReportInfoDao.class).clone();
        rabbitReportInfoDaoConfig.initIdentityScope(type);

        rabbitAppStartSpeedInfoDao = new RabbitAppStartSpeedInfoDao(rabbitAppStartSpeedInfoDaoConfig, this);
        rabbitBlockFrameInfoDao = new RabbitBlockFrameInfoDao(rabbitBlockFrameInfoDaoConfig, this);
        rabbitExceptionInfoDao = new RabbitExceptionInfoDao(rabbitExceptionInfoDaoConfig, this);
        rabbitFPSInfoDao = new RabbitFPSInfoDao(rabbitFPSInfoDaoConfig, this);
        rabbitHttpLogInfoDao = new RabbitHttpLogInfoDao(rabbitHttpLogInfoDaoConfig, this);
        rabbitMemoryInfoDao = new RabbitMemoryInfoDao(rabbitMemoryInfoDaoConfig, this);
        rabbitPageSpeedInfoDao = new RabbitPageSpeedInfoDao(rabbitPageSpeedInfoDaoConfig, this);
        rabbitReportInfoDao = new RabbitReportInfoDao(rabbitReportInfoDaoConfig, this);

        registerDao(RabbitAppStartSpeedInfo.class, rabbitAppStartSpeedInfoDao);
        registerDao(RabbitBlockFrameInfo.class, rabbitBlockFrameInfoDao);
        registerDao(RabbitExceptionInfo.class, rabbitExceptionInfoDao);
        registerDao(RabbitFPSInfo.class, rabbitFPSInfoDao);
        registerDao(RabbitHttpLogInfo.class, rabbitHttpLogInfoDao);
        registerDao(RabbitMemoryInfo.class, rabbitMemoryInfoDao);
        registerDao(RabbitPageSpeedInfo.class, rabbitPageSpeedInfoDao);
        registerDao(RabbitReportInfo.class, rabbitReportInfoDao);
    }
    
    public void clear() {
        rabbitAppStartSpeedInfoDaoConfig.clearIdentityScope();
        rabbitBlockFrameInfoDaoConfig.clearIdentityScope();
        rabbitExceptionInfoDaoConfig.clearIdentityScope();
        rabbitFPSInfoDaoConfig.clearIdentityScope();
        rabbitHttpLogInfoDaoConfig.clearIdentityScope();
        rabbitMemoryInfoDaoConfig.clearIdentityScope();
        rabbitPageSpeedInfoDaoConfig.clearIdentityScope();
        rabbitReportInfoDaoConfig.clearIdentityScope();
    }

    public RabbitAppStartSpeedInfoDao getRabbitAppStartSpeedInfoDao() {
        return rabbitAppStartSpeedInfoDao;
    }

    public RabbitBlockFrameInfoDao getRabbitBlockFrameInfoDao() {
        return rabbitBlockFrameInfoDao;
    }

    public RabbitExceptionInfoDao getRabbitExceptionInfoDao() {
        return rabbitExceptionInfoDao;
    }

    public RabbitFPSInfoDao getRabbitFPSInfoDao() {
        return rabbitFPSInfoDao;
    }

    public RabbitHttpLogInfoDao getRabbitHttpLogInfoDao() {
        return rabbitHttpLogInfoDao;
    }

    public RabbitMemoryInfoDao getRabbitMemoryInfoDao() {
        return rabbitMemoryInfoDao;
    }

    public RabbitPageSpeedInfoDao getRabbitPageSpeedInfoDao() {
        return rabbitPageSpeedInfoDao;
    }

    public RabbitReportInfoDao getRabbitReportInfoDao() {
        return rabbitReportInfoDao;
    }

}
